### ISSUE TITLE
Type mismatch error upon functor application

### ISSUE THREAD

**Issue by yizhou7** [secure-foundations/dafny#40]
```
abstract module PCM {
  type M
}
abstract module TicketStubSSM {
  type M(!new)
  predicate Internal(shard: M, shard': M)
}
module TicketStubPCM(ssm: TicketStubSSM) refines PCM {
  type M = ssm.M
}
module Tokens(pcm: PCM) {
    datatype Token = Token(ghost val: pcm.M)
}
module TicketStubToken(ssm: TicketStubSSM) {
  import pcm = TicketStubPCM(ssm)
  import Tokens = Tokens(pcm)
  type Token = Tokens.Token
  function method {:opaque} update_next(glinear a: Token, ghost expect_b: ssm.M): (glinear b: Token)
  requires ssm.Internal(a.val, expect_b)
}
module SSM refines TicketStubSSM {
}
module test {
  import Token = TicketStubToken(SSM) 
}
```

When the test module is added, a type mismatch error is raised on the line
`  requires ssm.Internal(a.val, expect_b)`
The error message is:
`Error: type mismatch for argument 0 (function expects M, got pcm.M)`
where the two types should be the same.

**Comment by parno** [comment]
Turns out the example you provided worked if you replaced 
```
  import pcm = TicketStubPCM(ssm)
  import Tokens = Tokens(pcm)
```
with 
```
import Tokens = Tokens(TicketStubPCM(ssm))
```
The problem was that `pcm` got updated correctly with `SSM`, but when we updated `Tokens(pcm)`, it used the old definition of `pcm`, namely `TicketStubPCM(ssm)`, due to some annoyances around how Dafny handles module aliases.  Commit 3b639cb tries to do a better job following through such aliases anyway.
